title: Services Configuration Files
description: Specifies managed configuration files for services
payload:
  declarationtype: com.apple.configuration.services.configuration-files
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '14.0'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  apply: multiple
payloadkeys:
- key: ServiceType
  title: Service Type
  type: <string>
  presence: required
  content: |-
    The identifier of the system service with managed configuration files. Use a reverse DNS style for this identifier. However, the system reserves 'com.apple.' prefix for built-in services. The available built-in services are:
    * 'com.apple.sshd' configures sshd
    * 'com.apple.sudo' configures sudo
    * 'com.apple.pam' configures PAM
    * 'com.apple.cups' configures CUPS
    * 'com.apple.apache.httpd' configures Apache httpd
    * 'com.apple.bash' configures bash
    * 'com.apple.zsh' configures zsh
- key: DataAssetReference
  title: Data Asset Reference
  type: <string>
  assettypes:
  - com.apple.asset.data
  asset-content-types:
  - application/zip
  presence: required
  content: |-
    The identifier of an asset declaration that contains a reference to the files to use for system service configuration. Ensure that the corresponding asset:

    * Is of type 'com.apple.asset.data'
    * Is a zip archive of an entire directory
    * Has a 'Reference' key that includes the 'ContentType' and 'Hash-SHA-256' keys, which the system requires

    The system expands the zip archive and stores the data in a well-known location for the service.
